export const krisengebiete = [
    "Kolumbien",
    "Chile",
    "Mali",
    "Nigeria",
    "Kamerun",
    "Zentralafrikanische Republik",
    "Demokratische Republik Kongo",
    "Äthiopien",
    "Südsudan",
    "Ägypten",
    "Somalia",
    "Mosambik",
    "Ukraine",
    "Türkei",
    "Syrien",
    "Irak",
    "Israel/ Palästina",
    "Jemen",
    "Afghanistan",
    "Pakistan",
    "Indien",
    "Indonesien",
    "Myanmar",
    "Thailand",
    "Philippinen",
];